import { z } from 'zod';
import { redactPII, verifyGroundedness, callGuardedAI } from '../services/ai';
import { evaluateNaranjo, naranjoAnalysisSchema } from '../services/naranjo';
import { generateEmbedding, upsertCaseVector, findDuplicateCase, clearMockQdrant } from '../services/dedup';
import { initQueue, enqueueCaseJob, closeQueue } from '../services/queue';
import { resetMockDb, casesTable, caseEventsTable, patientsTable, drugsTable } from '../config/mockDb';

describe('PharmaSafe Phase 2 - Core AI Pipeline Tests', () => {
  beforeEach(() => {
    resetMockDb();
    clearMockQdrant();
  });

  describe('PII Redactor and Date Offsets', () => {
    it('should redact emails, phone numbers, and name patterns', () => {
      const input = 'Patient John Doe at john.doe@email.com called from +1 555-123-4567. Ms. Sarah Chen reported rash.';
      const output = redactPII(input);

      expect(output).not.toContain('john.doe@email.com');
      expect(output).not.toContain('555-123-4567');
      expect(output).not.toContain('Sarah Chen');
      
      expect(output).toContain('[EMAIL_REDACTED]');
      expect(output).toContain('[PHONE_REDACTED]');
      expect(output).toContain('[NAME_REDACTED]');
    });

    it('should convert exact dates to relative offsets when onsetDate is provided', () => {
      const onsetDate = '2026-07-12';
      const input = 'Patient started treatment on 2026-07-10. Adverse reaction onset was on 2026-07-12. Lab test on 2026-07-15.';
      const output = redactPII(input, onsetDate);

      expect(output).toContain('day 2 pre-onset');
      expect(output).toContain('on the day of onset');
      expect(output).toContain('day 3 post-onset');
    });

    it('should fallback to [DATE_REDACTED] when no onsetDate is provided', () => {
      const input = 'Symptoms started on 2026-07-12.';
      const output = redactPII(input);
      expect(output).toContain('[DATE_REDACTED]');
    });
  });

  describe('Groundedness and Self-Consistency Verification', () => {
    it('should verify verbatim matching for groundedness', () => {
      const text = 'The patient experienced severe abdominal pain post ingestion.';
      
      expect(verifyGroundedness('abdominal pain', text)).toBe(true);
      expect(verifyGroundedness('ABDOMINAL PAIN', text)).toBe(true);
      expect(verifyGroundedness('abdominal   pain.', text)).toBe(true);
      expect(verifyGroundedness('mild headache', text)).toBe(false);
    });

    it('should validate LLM output schema and consistency', async () => {
      const narrative = 'Adverse drug event reported. Patient developed mild rash.';
      const testSchema = z.object({
        hasRash: z.enum(['yes', 'no', 'unknown']),
        supportingQuote: z.string()
      });
      
      const result = await callGuardedAI({
        prompt: 'Is there a rash?',
        narrative,
        responseSchema: testSchema
      });

      expect(result.data.hasRash).toBe('yes');
      expect(result.grounded).toBe(true);
      expect(result.selfConsistent).toBe(true);
      expect(result.redactedNarrative).toBeDefined();
    });
  });

  describe('Naranjo ADR Probability Scorer', () => {
    it('should execute scoring tally and assign the correct causality probability category', async () => {
      const narrative = 'Adverse drug event reported. Suspected drug given. Patient developed mild rash.';
      
      // Mock answers will be generated by simulateMockLLMResponse
      const result = await evaluateNaranjo(narrative);

      expect(result.score).toBeDefined();
      expect(result.category).toBeDefined();
      expect(result.answers.length).toBe(10);
      expect(result.grounded).toBe(true);
      expect(result.selfConsistent).toBe(true);
    });
  });

  describe('Vector Deduplication & Qdrant Integration', () => {
    const tenantId = 'de000000-0000-0000-0000-000000000001';
    
    it('should identify near duplicate case under same drug and tenant', async () => {
      const caseId1 = 'c0000001-1111-1111-1111-111111111111';
      const text1 = 'Patient experienced severe nausea after taking Metformin.';
      const vec1 = await generateEmbedding(text1);
      
      // Upsert Case 1
      await upsertCaseVector(caseId1, vec1, { tenantId, drugName: 'METFORMIN', narrative: text1 });

      // Search for duplicate with close text
      const text2 = 'nausea after Metformin intake.';
      const vec2 = await generateEmbedding(text2);

      const duplicateId = await findDuplicateCase(tenantId, 'METFORMIN', vec2);
      expect(duplicateId).toBe(caseId1);
    });

    it('should ignore matches on different drugs or tenants', async () => {
      const caseId1 = 'c0000001-1111-1111-1111-111111111111';
      const text1 = 'Patient experienced severe nausea after taking Metformin.';
      const vec1 = await generateEmbedding(text1);
      
      await upsertCaseVector(caseId1, vec1, { tenantId, drugName: 'METFORMIN', narrative: text1 });

      const vec2 = await generateEmbedding(text1);

      // Search on different drug name
      const diffDrugResult = await findDuplicateCase(tenantId, 'ASPIRIN', vec2);
      expect(diffDrugResult).toBeNull();

      // Search on different tenant
      const diffTenantResult = await findDuplicateCase('another-tenant-uuid', 'METFORMIN', vec2);
      expect(diffTenantResult).toBeNull();
    });
  });

  describe('Job Queue Orchestrator Pipeline', () => {
    const tenantId = 'de000000-0000-0000-0000-000000000001';

    beforeEach(async () => {
      await initQueue();
    });

    afterEach(async () => {
      await closeQueue();
    });

    it('should orchestrate case transitions from intake through Validity, Dedup, Triage, and Causality', async () => {
      // 1. Seed drug and patient in mock DB
      const drugId = 'd0000001-0000-0000-0000-000000000001';
      
      const patientRes = await patientsTable.push({
        id: 'p0000001-2222-2222-2222-222222222222',
        tenant_id: tenantId,
        age: 35,
        sex: 'female',
        created_at: new Date()
      });

      // 2. Create case
      const caseId = 'c0000001-3333-3333-3333-333333333333';
      casesTable.push({
        id: caseId,
        tenant_id: tenantId,
        patient_id: 'p0000001-2222-2222-2222-222222222222',
        drug_id: drugId,
        reporter_id: '55555555-5555-5555-5555-555555555555',
        reporter_type: 'healthcare_professional',
        dosage: '10mg',
        onset_date: new Date(),
        narrative: 'Patient experienced severe skin rash after drug intake.',
        hospitalization: true, // triggers high priority
        life_threatening: false,
        disability: false,
        status: 'intake',
        priority: null,
        source: 'manual',
        created_at: new Date(),
        updated_at: new Date()
      });

      // 3. Enqueue and trigger background processing
      await enqueueCaseJob(caseId);

      // Wait a short moment for async macro task execution to finish in mock queue
      await new Promise(r => setTimeout(r, 150));

      // 4. Verify case fields update
      const caseRecord = casesTable.find(c => c.id === caseId);
      expect(caseRecord).toBeDefined();
      expect(caseRecord?.status).toBe('triaged'); // Completed successfully
      expect(caseRecord?.priority).toBe('high'); // Updated by triage

      // 5. Verify audit logs are created
      expect(caseEventsTable.length).toBe(4);
      
      const actions = caseEventsTable.map(e => e.action);
      expect(actions).toContain('validity_checked');
      expect(actions).toContain('duplicate_checked');
      expect(actions).toContain('triage_prioritized');
      expect(actions).toContain('causality_evaluated');
    });
  });
});
